version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" # Map port 80 of the container to port 8080 on the host
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    restart: unless-stopped
